// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_bgX6_XlNfvIq9ec44rUt2yWhkRjEQEg',
    appId: '1:626065256298:web:889339734a5a0f48e2ff13',
    messagingSenderId: '626065256298',
    projectId: 'inkquesttattoo-f88ac',
    authDomain: 'inkquesttattoo-f88ac.firebaseapp.com',
    storageBucket: 'inkquesttattoo-f88ac.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYCquDA6UwA_XkG1NE7DY6zuxpQDkL4gM',
    appId: '1:626065256298:android:d470ad960a187377e2ff13',
    messagingSenderId: '626065256298',
    projectId: 'inkquesttattoo-f88ac',
    storageBucket: 'inkquesttattoo-f88ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAss4uO_GgtZ3k98d8D17n4_c1f1tfM_XQ',
    appId: '1:626065256298:ios:6af2932bca5e406ee2ff13',
    messagingSenderId: '626065256298',
    projectId: 'inkquesttattoo-f88ac',
    storageBucket: 'inkquesttattoo-f88ac.firebasestorage.app',
    iosBundleId: 'com.example.inkquestTattoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAss4uO_GgtZ3k98d8D17n4_c1f1tfM_XQ',
    appId: '1:626065256298:ios:6af2932bca5e406ee2ff13',
    messagingSenderId: '626065256298',
    projectId: 'inkquesttattoo-f88ac',
    storageBucket: 'inkquesttattoo-f88ac.firebasestorage.app',
    iosBundleId: 'com.example.inkquestTattoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_bgX6_XlNfvIq9ec44rUt2yWhkRjEQEg',
    appId: '1:626065256298:web:8d3a7ac9e060b9b5e2ff13',
    messagingSenderId: '626065256298',
    projectId: 'inkquesttattoo-f88ac',
    authDomain: 'inkquesttattoo-f88ac.firebaseapp.com',
    storageBucket: 'inkquesttattoo-f88ac.firebasestorage.app',
  );

}